require('dotenv').config();
const express=require('express'),pg=require('pg'),session=require('express-session'),bcrypt=require('bcryptjs'),crypto=require('crypto'),path=require('path');
const app=express(),{Pool}=pg,pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
if(process.env.NODE_ENV==='production' && (!process.env.SESSION_SECRET || process.env.SESSION_SECRET.length<32)) throw new Error('SESSION_SECRET debe tener al menos 32 caracteres en producción');
app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','DENY');next()});
const loginAttempts=new Map();
app.set('trust proxy',1);app.use(express.json({limit:'1mb'}));app.use(session({name:'ed.sid',secret:process.env.SESSION_SECRET||'development-only-change-this-secret-32chars',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:8*60*60*1000}}));
app.get('/api/auth/csrf',(req,res)=>{if(!req.session.csrf)req.session.csrf=crypto.randomBytes(32).toString('hex');res.json({csrf:req.session.csrf})});
app.use('/api', (req,res,next)=>{if(['GET','HEAD','OPTIONS'].includes(req.method)||req.path==='/auth/login'||req.path==='/auth/csrf')return next();const token=req.get('x-csrf-token');if(!req.session.csrf||token!==req.session.csrf)return res.status(403).json({error:'Token CSRF ausente o inválido'});next()});
const schema=`
CREATE TABLE IF NOT EXISTS usuarios(id SERIAL PRIMARY KEY,nombre TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,rol TEXT DEFAULT 'admin',creado_en TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS leads(id SERIAL PRIMARY KEY,nombre TEXT NOT NULL,email TEXT,telefono TEXT,origen TEXT,servicio TEXT,etapa TEXT DEFAULT 'Contactado',notas TEXT,creado_en TIMESTAMPTZ DEFAULT now(),actualizado_en TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS clientes(id SERIAL PRIMARY KEY,nombre TEXT NOT NULL,email TEXT,telefono TEXT,nacionalidad TEXT,documento TEXT,servicio TEXT,direccion TEXT,notas TEXT,fecha_alta DATE DEFAULT CURRENT_DATE,creado_en TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS expedientes(id SERIAL PRIMARY KEY,cliente_id INT REFERENCES clientes(id) ON DELETE CASCADE,tipo TEXT,fase TEXT DEFAULT 'Documentación pendiente',notas TEXT,fecha_apertura DATE DEFAULT CURRENT_DATE,creado_en TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS documentos(id SERIAL PRIMARY KEY,cliente_id INT REFERENCES clientes(id) ON DELETE CASCADE,tipo TEXT,estado TEXT DEFAULT 'Pendiente',fecha DATE,fecha_caducidad DATE,notas TEXT,creado_en TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS facturas(id SERIAL PRIMARY KEY,cliente_id INT REFERENCES clientes(id),numero TEXT UNIQUE,concepto TEXT,importe NUMERIC(12,2),fecha DATE DEFAULT CURRENT_DATE,estado TEXT DEFAULT 'Pendiente',creado_en TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS pagos(id SERIAL PRIMARY KEY,cliente_id INT REFERENCES clientes(id),concepto TEXT,importe NUMERIC(12,2),metodo TEXT,fecha DATE DEFAULT CURRENT_DATE,estado TEXT DEFAULT 'Confirmado',es_cuota BOOLEAN DEFAULT false,creado_en TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS financiaciones(id SERIAL PRIMARY KEY,cliente_id INT UNIQUE REFERENCES clientes(id) ON DELETE CASCADE,total NUMERIC(12,2),num_cuotas INT,fecha_inicio DATE,periodicidad TEXT,notas TEXT,creado_en TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS seguimientos(id SERIAL PRIMARY KEY,cliente_id INT REFERENCES clientes(id) ON DELETE CASCADE,lead_id INT REFERENCES leads(id) ON DELETE CASCADE,contacto TEXT,tipo TEXT,fecha DATE DEFAULT CURRENT_DATE,proximo_contacto DATE,notas TEXT,creado_en TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS webhook_tokens(id SERIAL PRIMARY KEY,token TEXT UNIQUE NOT NULL,descripcion TEXT,activo BOOLEAN DEFAULT true,creado_en TIMESTAMPTZ DEFAULT now());`;
const auth=(req,res,next)=>req.session.user?next():res.status(401).json({error:'No autorizado'}),admin=(req,res,next)=>req.session.user?.rol==='admin'?next():res.sendStatus(403);
app.post('/api/auth/login',async(req,res)=>{const ip=req.ip||'unknown',now=Date.now(),a=loginAttempts.get(ip)||{count:0,until:0};if(a.until>now)return res.status(429).json({error:'Demasiados intentos. Espera unos minutos.'});const {email,password}=req.body||{};const r=await pool.query('SELECT id,nombre,email,password_hash,rol FROM usuarios WHERE lower(email)=lower($1)',[email]);if(!r.rowCount||!await bcrypt.compare(password||'',r.rows[0].password_hash)){a.count++;if(a.count>=8){a.until=now+15*60*1000;a.count=0}loginAttempts.set(ip,a);return res.status(401).json({error:'Credenciales incorrectas'})}loginAttempts.delete(ip);const u=r.rows[0];delete u.password_hash;req.session.user=u;res.json(u)});
app.post('/api/auth/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));app.get('/api/auth/me',(req,res)=>res.json(req.session.user||null));
app.post('/api/webhook/lead',async(req,res)=>{const token=req.get('x-webhook-token')||req.query.token;const t=await pool.query('SELECT id FROM webhook_tokens WHERE token=$1 AND activo=true',[token]);if(!t.rowCount)return res.sendStatus(401);const {nombre,email,telefono,origen,servicio,notas}=req.body||{};if(!nombre)return res.status(400).json({error:'nombre requerido'});if(email){const c=await pool.query('SELECT id FROM clientes WHERE lower(email)=lower($1) LIMIT 1',[email]);if(c.rowCount){await pool.query("INSERT INTO seguimientos(cliente_id,contacto,tipo,notas) VALUES($1,$2,'Email',$3)",[c.rows[0].id,nombre,notas||'Nuevo contacto desde webhook']);return res.json({status:'seguimiento_creado'})}const l=await pool.query("SELECT id FROM leads WHERE lower(email)=lower($1) AND etapa NOT IN ('Cerrado ganado','Cerrado perdido') LIMIT 1",[email]);if(l.rowCount)return res.json({status:'lead_existente',id:l.rows[0].id})}const r=await pool.query("INSERT INTO leads(nombre,email,telefono,origen,servicio,notas) VALUES($1,$2,$3,$4,$5,$6) RETURNING id",[nombre,email,telefono,origen||'Web',servicio,notas]);res.status(201).json({status:'creado',id:r.rows[0].id})});
app.use('/api',auth);
const routes={leads:['leads','nombre,email,telefono,origen,servicio,etapa,notas'],clientes:['clientes','nombre,email,telefono,nacionalidad,documento,servicio,direccion,notas,fecha_alta,fecha_nacimiento,ciudad,codigo_postal,pais_origen,familiares,documentacion,condiciones_pago,proximo_seguimiento,estado_cliente'],expedientes:['expedientes','cliente_id,tipo,fase,notas,fecha_apertura'],documentos:['documentos','cliente_id,tipo,estado,fecha,fecha_caducidad,notas'],facturas:['facturas','cliente_id,concepto,importe,fecha,estado'],pagos:['pagos','cliente_id,concepto,importe,metodo,fecha,estado,es_cuota'],seguimientos:['seguimientos','cliente_id,lead_id,contacto,tipo,fecha,proximo_contacto,notas']};
for(const [url,[table,cols]] of Object.entries(routes)){app.get('/api/'+url,async(req,res)=>{const r=await pool.query(`SELECT * FROM ${table} ORDER BY creado_en DESC`);res.json(r.rows)});app.post('/api/'+url,async(req,res)=>{const keys=cols.split(',').filter(k=>req.body[k]!==undefined);const vals=keys.map(k=>req.body[k]);if(table==='facturas'){const n=await pool.query("SELECT COALESCE(MAX(id),0)+1 n FROM facturas");vals.splice(keys.indexOf('concepto'),0);keys.push('numero');vals.push('FAC-'+String(n.rows[0].n).padStart(4,'0'))}const sql=`INSERT INTO ${table}(${keys.join(',')}) VALUES(${keys.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING *`;res.status(201).json((await pool.query(sql,vals)).rows[0])})}
for(const [url,[table,cols]] of Object.entries(routes)){
 const allowed=cols.split(',');
 app.put('/api/'+url+'/:id',async(req,res)=>{const keys=allowed.filter(k=>req.body[k]!==undefined);if(!keys.length)return res.status(400).json({error:'No hay campos válidos para actualizar'});const vals=keys.map(k=>req.body[k]);vals.push(req.params.id);const sql=`UPDATE ${table} SET ${keys.map((k,i)=>k+'=$'+(i+1)).join(',')} WHERE id=$${vals.length} RETURNING *`;const r=await pool.query(sql,vals);if(!r.rowCount)return res.sendStatus(404);res.json(r.rows[0])});
 app.delete('/api/'+url+'/:id',admin,async(req,res)=>{const r=await pool.query(`DELETE FROM ${table} WHERE id=$1 RETURNING id`,[req.params.id]);if(!r.rowCount)return res.sendStatus(404);res.json({ok:true})});
}
app.put('/api/leads/:id',async(req,res)=>{const {etapa,notas}=req.body;res.json((await pool.query('UPDATE leads SET etapa=COALESCE($1,etapa),notas=COALESCE($2,notas),actualizado_en=now() WHERE id=$3 RETURNING *',[etapa,notas,req.params.id])).rows[0])});
app.post('/api/leads/:id/convertir',async(req,res)=>{const c=await pool.connect();try{await c.query('BEGIN');const l=(await c.query('SELECT * FROM leads WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!l)throw Error('Lead no encontrado');const cl=(await c.query('INSERT INTO clientes(nombre,email,telefono,servicio,notas) VALUES($1,$2,$3,$4,$5) RETURNING *',[l.nombre,l.email,l.telefono,l.servicio,l.notas])).rows[0];const ex=await c.query("INSERT INTO expedientes(cliente_id,tipo,fase) VALUES($1,$2,'Documentación pendiente') RETURNING *",[cl.id,l.servicio]);await c.query("UPDATE leads SET etapa='Cerrado ganado',actualizado_en=now() WHERE id=$1",[l.id]);await c.query('COMMIT');res.json({cliente:cl,expediente:ex.rows[0]})}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message})}finally{c.release()}});
app.get('/api/dashboard',async(req,res)=>{const q=await pool.query(`SELECT (SELECT count(*) FROM leads WHERE etapa NOT LIKE 'Cerrado%') leads_activos,(SELECT count(*) FROM leads WHERE etapa='Propuesta enviada') propuestas,(SELECT count(*) FROM clientes) clientes,(SELECT count(*) FROM expedientes WHERE fase<>'Finalizado') expedientes_abiertos,(SELECT COALESCE(sum(importe),0) FROM facturas WHERE date_trunc('month',fecha)=date_trunc('month',CURRENT_DATE)) facturado_mes,(SELECT COALESCE(sum(importe),0) FROM pagos WHERE estado='Confirmado' AND date_trunc('month',fecha)=date_trunc('month',CURRENT_DATE)) cobrado_mes,(SELECT COALESCE(sum(importe),0) FROM facturas WHERE estado<>'Cobrada') pendiente_cobro`);res.json(q.rows[0])});
app.get('/api/buscar',async(req,res)=>{const q='%'+String(req.query.q||'').slice(0,100)+'%';const r=await pool.query("SELECT 'cliente' tipo,id,nombre etiqueta FROM clientes WHERE nombre ILIKE $1 OR email ILIKE $1 OR telefono ILIKE $1 UNION ALL SELECT 'lead',id,nombre FROM leads WHERE nombre ILIKE $1 OR email ILIKE $1 UNION ALL SELECT 'factura',id,numero FROM facturas WHERE numero ILIKE $1 LIMIT 30",[q]);res.json(r.rows)});
app.get('/api/webhook/token',admin,async(req,res)=>res.json((await pool.query('SELECT id,token,descripcion,creado_en FROM webhook_tokens WHERE activo=true')).rows));app.post('/api/webhook/token/nuevo',admin,async(req,res)=>{await pool.query('UPDATE webhook_tokens SET activo=false');const token=crypto.randomBytes(32).toString('hex');res.json((await pool.query('INSERT INTO webhook_tokens(token,descripcion) VALUES($1,$2) RETURNING id,token',[token,'Integración CRM'])).rows[0])});
app.use((err,req,res,next)=>{console.error('API error:',err.message);if(res.headersSent)return next(err);res.status(500).json({error:'Error interno. Revisa los logs del servidor.'})});
app.use(express.static(path.join(__dirname,'public')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public/index.html')));
(async()=>{await pool.query(schema);
await pool.query(`ALTER TABLE clientes ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE, ADD COLUMN IF NOT EXISTS ciudad TEXT, ADD COLUMN IF NOT EXISTS codigo_postal TEXT, ADD COLUMN IF NOT EXISTS pais_origen TEXT, ADD COLUMN IF NOT EXISTS familiares TEXT, ADD COLUMN IF NOT EXISTS documentacion TEXT, ADD COLUMN IF NOT EXISTS condiciones_pago TEXT, ADD COLUMN IF NOT EXISTS proximo_seguimiento TEXT, ADD COLUMN IF NOT EXISTS estado_cliente TEXT`);
if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD){const hash=await bcrypt.hash(process.env.ADMIN_PASSWORD,12);await pool.query('INSERT INTO usuarios(nombre,email,password_hash,rol) VALUES($1,$2,$3,$4) ON CONFLICT(email) DO NOTHING',['Administrador',process.env.ADMIN_EMAIL,hash,'admin'])}const t=await pool.query('SELECT token FROM webhook_tokens WHERE activo=true LIMIT 1');if(!t.rowCount){const token=crypto.randomBytes(32).toString('hex');await pool.query('INSERT INTO webhook_tokens(token,descripcion) VALUES($1,$2)',[token,'Token inicial']);console.log('Token webhook inicial creado. Consulta/regenera desde el panel de administración; no se imprime por seguridad.')}app.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('CRM listo'))})().catch(e=>{console.error(e);process.exit(1)});
